spring:
  application:
    name: Human Resource
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5433/humanresource}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:020775Rashy!}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

server:
  port: 9004