spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5433/humanresource}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:020775Rashy!}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        types:
          print:
            banner: false
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  ai:
    openai:
      api-key: ${openaiAPI_KEY}
      model: gpt-4o-mini
      chat:
        options:
          model: gpt-4o-mini
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:https://ngcloak-production.up.railway.app/realms/humanResources}

        registration:
          keycloak:
            provider: keycloak
            client_id: ${KEYCLOAK_CLIENT_ID:humanResources}
            client_secret: ${KEYCLOAK_CLIENT_SECRET:SA4ldpRWyPv8UPJYwi5qBNX2GWs5tYlM}
            authorization-grant-type: authorization_code
            scope: openid,profile,email

          keycloak-mobile:
            provider: keycloak
            client_id: ${KEYCLOAK_CLIENT_ID:humanResources}
            client_secret: ${KEYCLOAK_CLIENT_SECRET:SA4ldpRWyPv8UPJYwi5qBNX2GWs5tYlM}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      ProcessModelIdUnique: PROCESS_MODEL_ID_UNIQUE
      ProcessProcessNameUnique: PROCESS_PROCESS_NAME_UNIQUE
      ValidFileType: VALID_FILE_TYPE
server:
  tomcat:
    max-part-count: '100'

springdoc:
  pathsToMatch: /api/**
keycloak:
  base-url: ${KEYCLOAK_BASE_URI:https://ngcloak-production.up.railway.app}
  client-id: ${KEYCLOAK_CLIENT_ID:humanResources}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:SA4ldpRWyPv8UPJYwi5qBNX2GWs5tYlM}
