name: build-JustHumanResource
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
#          cache: maven

      - name: Install glibc
        run: sudo apt-get update && sudo apt-get install -y libc6


  build-image:
    name: Build and push to docker
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and Push with Jib
        run: mvn -B clean package jib:build -Djib.to.image=kazeemakinrinde/justhumanresource:latest -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}
#        run: mvn -B clean package jib:build -Djib.to.image=kazeemakinrinde/csims:latest -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}


  deploy:
    name: deploy to railway
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Install Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest

      - name: Print Railway CLI version
        run: railway --version

      - name: Print Help
        run: railway variables --help


      # - name: Deploy to Railway
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      #     RAILWAY_PROJECT_ID: 7edc707c-73e3-4b8b-915b-019e9d0b6114
      #     RAILWAY_SERVICE_ID: justhumanresource
      #   run: |
      #     IMAGE_REF="justhumanresource:latest"
      #     echo "Updating service image to: $IMAGE_REF"
      #     railway variables --set "RAILWAY_SERVICE_IMAGE=$IMAGE_REF" --service $RAILWAY_SERVICE_ID
          
          
          